title: Lerntagebuch Bibliotheks- und Archivinformatik
author: Yannick Leu
email: yannick.leu@stud.fhgr.ch
description: > # this means to ignore newlines
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2023


show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
